spring.application.name=continuum-control

# Configuração de conexão com o PostgreSQL do Docker
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

# Dialeto do PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update

# Exibir SQL no console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true